package com.nm.fragmentsclean.experienceContextTest.endtoend;
import com.nm.fragmentsclean.sharedKernel.adapters.secondary.gateways.providers.DeterministicDateTimeProvider;import com.nm.fragmentsclean.sharedKernel.businesslogic.models.DateTimeProvider;import com.nm.fragmentsclean.sharedKernel.businesslogic.media.PrivateImageStore;import java.net.URI;import java.time.*;import java.util.Map;import org.springframework.boot.test.context.TestConfiguration;import org.springframework.context.annotation.*;
@TestConfiguration public class ExperienceContextE2EConfiguration{
@Primary @Bean FakeImageAnalyzer fakeImageAnalyzer(){return new FakeImageAnalyzer();}
public static class FakeImageAnalyzer implements com.nm.fragmentsclean.sharedKernel.businesslogic.media.ImageContentAnalyzer {
 public boolean flagged;public boolean unavailable;public int calls;
 public boolean flagged(URI image){if(org.springframework.transaction.support.TransactionSynchronizationManager.isActualTransactionActive())throw new AssertionError("Moderation inside transaction");calls++;if(unavailable)throw new IllegalStateException("Moderation unavailable");return flagged;}
}
@Primary @Bean DateTimeProvider deterministicExperienceClock(){return new DeterministicDateTimeProvider();}@Primary@Bean PrivateImageStore deterministicPrivateImageStore(FakeImageAnalyzer analyzer){return new PrivateImageStore(){private void outsideTransaction(){if(org.springframework.transaction.support.TransactionSynchronizationManager.isActualTransactionActive())throw new AssertionError("Remote object storage call inside database transaction");}public UploadTarget presignUpload(String key,String type,Duration ttl,Instant at){outsideTransaction();return new UploadTarget(URI.create("https://upload.test/object"),"PUT",Map.of("Content-Type",type),at.plus(ttl));}public ProcessedImage normalize(String pending,String target,String type,ImageRules rules){outsideTransaction();return new ProcessedImage(target,"image/jpeg",640,Math.min(1200,rules.maxWidth()),Math.min(800,rules.maxHeight()),"test-sha",analyzer.flagged(URI.create("https://download.test/"+target)));}public URI presignDownload(String key,Duration ttl){outsideTransaction();return URI.create("https://download.test/"+key);}public void delete(String key){outsideTransaction();}};}}
