package com.nm.fragmentsclean.coffeeContextTest.unit;
import java.time.*;import java.util.*;import org.junit.jupiter.api.Test;import static org.assertj.core.api.Assertions.*;
import com.nm.fragmentsclean.coffeeContext.write.businessLogic.models.*;
import com.nm.fragmentsclean.coffeeContext.write.businessLogic.models.VO.*;
import com.nm.fragmentsclean.coffeeContext.write.businessLogic.gateways.*;
import com.nm.fragmentsclean.coffeeContext.write.businessLogic.usecases.*;
import com.nm.fragmentsclean.coffeeContext.write.adapters.secondary.gateways.repositories.fakes.*;
import com.nm.fragmentsclean.sharedKernel.adapters.secondary.gateways.providers.outboxEventPublisher.FakeDomainEventPublisher;
class CoffeeMediaReplacementTest {
 final UUID coffeeId=UUID.randomUUID(),oldId=UUID.randomUUID(),otherId=UUID.randomUUID(),commandId=UUID.randomUUID(),actor=UUID.randomUUID();final Instant now=Instant.parse("2026-10-05T10:00:00Z");
 final FakeCoffeeRepository coffees=new FakeCoffeeRepository();final FakeCoffeePhotoRetirementRepository memory=new FakeCoffeePhotoRetirementRepository();final FakeDomainEventPublisher events=new FakeDomainEventPublisher();final CoffeeMediaLifecycleHandlerTest.RecordingAudit audit=new CoffeeMediaLifecycleHandlerTest.RecordingAudit();final RecordingStorage storage=new RecordingStorage();
 CoffeeMediaReplacementTest(){new CreateCoffeeCommandHandler(coffees,events,()->now).execute(new CreateCoffeeCommand(UUID.randomUUID(),coffeeId,null,"Replace","Street","Paris","75000","FR",0,0,null,null,List.of(),now));var c=coffees.findById(new CoffeeId(coffeeId)).orElseThrow();c.addPhoto(new Photo(new PhotoId(otherId),c.coffeeId(),"https://images.test/other",true,0),now);c.addPhoto(new Photo(new PhotoId(oldId),c.coffeeId(),"https://images.test/old",false,1),now);c.arrangePhotos(List.of(new PhotoId(otherId),new PhotoId(oldId)),new PhotoId(oldId),now);coffees.save(c);events.published.clear();}
 ReplaceCoffeeMediaCommand command(){return new ReplaceCoffeeMediaCommand(commandId,coffeeId,oldId,actor,"new.png","image/png",new byte[]{1}," New cover ");}
 ReplaceCoffeeMediaCommandHandler handler(){return new ReplaceCoffeeMediaCommandHandler(coffees,memory,storage,events,audit,()->now);}
 @Test void replacement_preserves_order_and_cover_and_retains_original_with_audit_and_inventory(){
  int version=coffees.findById(new CoffeeId(coffeeId)).orElseThrow().version();handler().execute(command());var current=coffees.findById(new CoffeeId(coffeeId)).orElseThrow();var newId=CoffeePhotoStorage.photoId(current.coffeeId(),"admin-upload/"+commandId+"/new.png");assertThat(current.photos()).extracting(p->p.id().value()).containsExactly(otherId,newId);assertThat(current.photos().get(1).isCover()).isTrue();assertThat(current.photos().getFirst().isCover()).isFalse();assertThat(current.version()).isEqualTo(version+1);assertThat(memory.byId(oldId)).isPresent();assertThat(memory.byId(oldId).orElseThrow().photo().uri()).isEqualTo("https://images.test/old");assertThat(memory.byId(oldId).orElseThrow().retiredAt()).isEqualTo(now);assertThat(storage.calls).hasSize(1);assertThat(storage.deleted).isEmpty();assertThat(events.published).hasSize(2);var inventory=(CoffeeMediaCatalogSnapshotEvent)events.published.get(1);assertThat(inventory.retiredPhotos()).containsExactly(new CoffeeMediaCatalogSnapshotEvent.RetiredPhoto(oldId,now));assertThat(inventory.photos()).extracting(CoffeePhotosArrangedEvent.ArrangedPhoto::photoId).containsExactly(otherId,newId);assertThat(audit.decisions).containsExactly("COFFEE_MEDIA_REPLACED:New cover:"+actor,"COFFEE_MEDIA_REPLACEMENT_ADDED:New cover:"+actor);
 }
 @Test void archived_missing_ambiguous_and_retired_photos_reject_before_storage(){
  memory.currentCounts.put(oldId,2L);assertThatThrownBy(()->handler().execute(command())).hasMessageContaining("replacement rejected");assertThat(storage.calls).isEmpty();memory.currentCounts.clear();
  var invalid=new ReplaceCoffeeMediaCommand(commandId,coffeeId,UUID.randomUUID(),actor,"new.png","image/png",new byte[]{1},"Review");assertThatThrownBy(()->handler().execute(invalid)).hasMessageContaining("replacement rejected");assertThat(storage.calls).isEmpty();
  memory.save(new CoffeePhotoRetirement(coffees.findById(new CoffeeId(coffeeId)).orElseThrow().photos().get(1),now));assertThatThrownBy(()->handler().execute(command())).hasMessageContaining("replacement rejected");assertThat(storage.calls).isEmpty();memory.remove(oldId);var c=coffees.findById(new CoffeeId(coffeeId)).orElseThrow();c.archive(now);coffees.save(c);assertThatThrownBy(()->handler().execute(command())).hasMessageContaining("replacement rejected");assertThat(storage.calls).isEmpty();
 }
 @Test void storage_failure_leaves_original_gallery_and_no_retirement_or_success_audit(){storage.fail=true;assertThatThrownBy(()->handler().execute(command())).hasMessageContaining("storage unavailable");assertThat(coffees.findById(new CoffeeId(coffeeId)).orElseThrow().photos()).extracting(p->p.id().value()).containsExactly(otherId,oldId);assertThat(memory.items).isEmpty();assertThat(events.published).isEmpty();assertThat(audit.decisions).isEmpty();}
 @Test void identity_already_used_by_a_legacy_foreign_photo_rejects_before_storage(){
  var expected=CoffeePhotoStorage.photoId(new CoffeeId(coffeeId),"admin-upload/"+commandId+"/new.png");memory.currentCounts.put(expected,1L);assertThatThrownBy(()->handler().execute(command())).isInstanceOf(com.nm.fragmentsclean.sharedKernel.businesslogic.commandStatus.BusinessCommandRejectedException.class);assertThat(storage.calls).isEmpty();assertThat(memory.items).isEmpty();
 }
 @Test void invalid_image_or_reason_is_rejected_before_storage(){
  var invalids=List.of(new ReplaceCoffeeMediaCommand(commandId,coffeeId,oldId,actor,"new.png","image/png",new byte[]{1}," "),new ReplaceCoffeeMediaCommand(commandId,coffeeId,oldId,actor,"new.svg","image/svg+xml",new byte[]{1},"Review"),new ReplaceCoffeeMediaCommand(commandId,coffeeId,oldId,actor,"new.png","image/png",new byte[0],"Review"));
  for(var request:invalids)assertThatThrownBy(()->handler().execute(request)).isInstanceOf(com.nm.fragmentsclean.sharedKernel.businesslogic.commandStatus.BusinessCommandRejectedException.class);assertThat(storage.calls).isEmpty();assertThat(memory.items).isEmpty();
 }
 @Test void replacement_command_defensively_copies_file_bytes(){byte[] bytes={1};var request=new ReplaceCoffeeMediaCommand(commandId,coffeeId,oldId,actor,"new.png","image/png",bytes,"Review");bytes[0]=2;request.bytes()[0]=3;assertThat(request.bytes()).containsExactly((byte)1);}
 static class RecordingStorage implements CoffeePhotoStorage{boolean fail;final List<String>calls=new ArrayList<>();final List<UUID>deleted=new ArrayList<>();public ImportedCoffeePhoto store(CoffeeId c,GooglePlaceId g,GooglePlacePhoto p){if(fail)throw new IllegalStateException("storage unavailable");calls.add(p.sourceName());var id=CoffeePhotoStorage.photoId(c,p.sourceName());return new ImportedCoffeePhoto(id,"/api/coffees/photo-assets/"+id+".png");}public void deletePhoto(CoffeeId c,UUID id,String ref){deleted.add(id);}}
}
