package com.nm.fragmentsclean.articleContextTest.unit;
import java.util.*;import java.time.Instant;import org.junit.jupiter.api.Test;import static org.assertj.core.api.Assertions.*;
import com.nm.fragmentsclean.articleContext.write.businesslogic.gateways.*;import com.nm.fragmentsclean.articleContext.write.businesslogic.models.ArticleMediaLifecycle;import com.nm.fragmentsclean.articleContext.write.businesslogic.usecases.article.*;import com.nm.fragmentsclean.sharedKernel.businesslogic.models.AdminAuditRecorder;
class ArticleMediaLifecycleHandlerTest {
 static class FakeLifecycle implements ArticleMediaLifecycleRepository {ArticleMediaLifecycle value=new ArticleMediaLifecycle(UUID.randomUUID(),UUID.randomUUID(),"ref","ACTIVE",0);int writes;public List<UUID> pendingPurgeIds(int limit){return List.of();}public Optional<ArticleMediaLifecycle> lock(UUID id){return Optional.ofNullable(value);}public void change(UUID id,String status,Instant at){writes++;value=new ArticleMediaLifecycle(value.mediaId(),value.articleId(),value.reference(),status,value.usages(),at);}}
 static class FakePurgeCapability implements ArticleMediaPurgeCapability {boolean allowed=true;public boolean supports(UUID article,String ref){return allowed;}}
 static class FakeAudit implements AdminAuditRecorder {List<String> reasons=new ArrayList<>();List<UUID> actors=new ArrayList<>();public void record(UUID a,String b,String c,UUID d,UUID e,String f,Instant g){}public void recordDecision(UUID actor,String action,String target,UUID media,UUID command,String outcome,String reason,Instant at){reasons.add(reason);actors.add(actor);}}
 @Test void validates_reason_before_mutation_and_audits_success_with_operator(){var repo=new FakeLifecycle();var audit=new FakeAudit();var catalogue=new FakeArticleMediaCatalogPublisher();var handler=new ChangeArticleMediaLifecycleCommandHandler(repo,catalogue,audit,Instant::now,new FakePurgeCapability());UUID actor=UUID.randomUUID();
  assertThatThrownBy(()->handler.execute(new ChangeArticleMediaLifecycleCommand(UUID.randomUUID(),repo.value.mediaId(),actor,"RETIRED"," "))).hasMessageContaining("reason");assertThat(repo.writes).isZero();assertThat(audit.reasons).isEmpty();
  handler.execute(new ChangeArticleMediaLifecycleCommand(UUID.randomUUID(),repo.value.mediaId(),actor,"RETIRED"," Obsolete "));assertThat(repo.value.status()).isEqualTo("RETIRED");assertThat(audit.reasons).containsExactly("Obsolete");assertThat(audit.actors).containsExactly(actor);assertThat(catalogue.published).containsExactly(repo.value.articleId());
 }
 @Test void used_or_missing_upload_never_changes_or_publishes(){var repo=new FakeLifecycle();repo.value=new ArticleMediaLifecycle(repo.value.mediaId(),repo.value.articleId(),"ref","ACTIVE",1);var audit=new FakeAudit();var catalogue=new FakeArticleMediaCatalogPublisher();var handler=new ChangeArticleMediaLifecycleCommandHandler(repo,catalogue,audit,Instant::now,new FakePurgeCapability());var command=new ChangeArticleMediaLifecycleCommand(UUID.randomUUID(),repo.value.mediaId(),UUID.randomUUID(),"RETIRED","Unused");assertThatThrownBy(()->handler.execute(command)).hasMessageContaining("referenced");repo.value=null;assertThatThrownBy(()->handler.execute(command)).hasMessageContaining("not found");assertThat(repo.writes).isZero();assertThat(audit.reasons).isEmpty();assertThat(catalogue.published).isEmpty();}
 @Test void purge_uses_the_source_capability_and_audits_the_request_instead_of_physical_completion(){
  var repo=new FakeLifecycle();var retired=Instant.parse("2026-09-01T00:00:00Z");var now=retired.plus(java.time.Duration.ofDays(30));repo.value=new ArticleMediaLifecycle(repo.value.mediaId(),repo.value.articleId(),"managed","RETIRED",0,retired);
  var capability=new FakePurgeCapability();capability.allowed=false;var audit=new FakeAudit();var catalogue=new FakeArticleMediaCatalogPublisher();var handler=new ChangeArticleMediaLifecycleCommandHandler(repo,catalogue,audit,()->now,capability);var actor=UUID.randomUUID();var command=new ChangeArticleMediaLifecycleCommand(UUID.randomUUID(),repo.value.mediaId(),actor,"PURGE_REQUESTED"," Explicit cleanup ");
  assertThatThrownBy(()->handler.execute(command)).hasMessageContaining("configured Article");assertThat(repo.writes).isZero();assertThat(audit.reasons).isEmpty();
  capability.allowed=true;handler.execute(command);assertThat(repo.value.status()).isEqualTo("DELETION_PENDING");assertThat(audit.reasons).containsExactly("Explicit cleanup");assertThat(audit.actors).containsExactly(actor);assertThat(catalogue.published).containsExactly(repo.value.articleId());
 }
}
