package com.nm.fragmentsclean.articleContextTest.unit;
import java.util.*;import java.time.Instant;import org.junit.jupiter.api.Test;import static org.assertj.core.api.Assertions.*;
import com.nm.fragmentsclean.articleContext.write.businesslogic.gateways.*;import com.nm.fragmentsclean.articleContext.write.businesslogic.models.ArticleMediaLifecycle;import com.nm.fragmentsclean.articleContext.write.businesslogic.usecases.article.*;import com.nm.fragmentsclean.sharedKernel.businesslogic.models.AdminAuditRecorder;
class ArticleMediaLifecycleHandlerTest {
 static class FakeLifecycle implements ArticleMediaLifecycleRepository {ArticleMediaLifecycle value=new ArticleMediaLifecycle(UUID.randomUUID(),UUID.randomUUID(),"ref","ACTIVE",0);int writes;public Optional<ArticleMediaLifecycle> lock(UUID id){return Optional.ofNullable(value);}public void change(UUID id,String status,Instant at){writes++;value=new ArticleMediaLifecycle(value.mediaId(),value.articleId(),value.reference(),status,value.usages());}}
 static class FakeAudit implements AdminAuditRecorder {List<String> reasons=new ArrayList<>();List<UUID> actors=new ArrayList<>();public void record(UUID a,String b,String c,UUID d,UUID e,String f,Instant g){}public void recordDecision(UUID actor,String action,String target,UUID media,UUID command,String outcome,String reason,Instant at){reasons.add(reason);actors.add(actor);}}
 @Test void validates_reason_before_mutation_and_audits_success_with_operator(){var repo=new FakeLifecycle();var audit=new FakeAudit();var catalogue=new FakeArticleMediaCatalogPublisher();var handler=new ChangeArticleMediaLifecycleCommandHandler(repo,catalogue,audit,Instant::now);UUID actor=UUID.randomUUID();
  assertThatThrownBy(()->handler.execute(new ChangeArticleMediaLifecycleCommand(UUID.randomUUID(),repo.value.mediaId(),actor,"RETIRED"," "))).hasMessageContaining("reason");assertThat(repo.writes).isZero();assertThat(audit.reasons).isEmpty();
  handler.execute(new ChangeArticleMediaLifecycleCommand(UUID.randomUUID(),repo.value.mediaId(),actor,"RETIRED"," Obsolete "));assertThat(repo.value.status()).isEqualTo("RETIRED");assertThat(audit.reasons).containsExactly("Obsolete");assertThat(audit.actors).containsExactly(actor);assertThat(catalogue.published).containsExactly(repo.value.articleId());
 }
 @Test void used_or_missing_upload_never_changes_or_publishes(){var repo=new FakeLifecycle();repo.value=new ArticleMediaLifecycle(repo.value.mediaId(),repo.value.articleId(),"ref","ACTIVE",1);var audit=new FakeAudit();var catalogue=new FakeArticleMediaCatalogPublisher();var handler=new ChangeArticleMediaLifecycleCommandHandler(repo,catalogue,audit,Instant::now);var command=new ChangeArticleMediaLifecycleCommand(UUID.randomUUID(),repo.value.mediaId(),UUID.randomUUID(),"RETIRED","Unused");assertThatThrownBy(()->handler.execute(command)).hasMessageContaining("referenced");repo.value=null;assertThatThrownBy(()->handler.execute(command)).hasMessageContaining("not found");assertThat(repo.writes).isZero();assertThat(audit.reasons).isEmpty();assertThat(catalogue.published).isEmpty();}
}
