-- Stable keyset ordering for the private per-user ticket history.
-- PostgreSQL assigns a position to existing rows when the identity column is added.
ALTER TABLE ticket_status_projection
    ADD COLUMN IF NOT EXISTS history_position BIGINT GENERATED BY DEFAULT AS IDENTITY;

CREATE UNIQUE INDEX IF NOT EXISTS idx_ticket_status_history_position
    ON ticket_status_projection(history_position);

CREATE INDEX IF NOT EXISTS idx_ticket_status_user_history
    ON ticket_status_projection(user_id, history_position DESC);
